AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Environment:
      Variables:
        TABLE_NAME: serverless2049-dynamodb-table-Database
    FunctionUrlConfig:
      AuthType: NONE
    MemorySize: 512
    Timeout: 30

Resources:

  Java11Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./java-function
      FunctionName: serverless2049-scenario01-function-Java11Function
      Handler: com.lineup.scenario01.function.java.Function
      Runtime: java11
      Policies:
        - AmazonDynamoDBFullAccess

  Java11ArmFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./java-function
      FunctionName: serverless2049-scenario01-function-Java11ArmFunction
      Handler: com.lineup.scenario01.function.java.Function
      Runtime: java11
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
        - arm64

  Java11SnapStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./java-function
      FunctionName: serverless2049-scenario01-function-Java11SnapStartFunction
      Handler: com.lineup.scenario01.function.java.Function
      Runtime: java11
      Policies:
        - AmazonDynamoDBFullAccess
      AutoPublishAlias: snap
      SnapStart:
        ApplyOn: PublishedVersions

  GraalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: java-function/native.zip
      FunctionName: serverless2049-scenario01-function-GraalFunction
      Handler: com.lineup.scenario01.function.java.Function
      Runtime: provided.al2
      Policies:
        - AmazonDynamoDBFullAccess

  QuarkusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: quarkus-function/target/function.zip
      FunctionName: serverless2049-scenario01-function-QuarkusFunction
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Policies:
        - AmazonDynamoDBFullAccess

  QuarkusGraalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: quarkus-function/native/function.zip
      FunctionName: serverless2049-scenario01-function-QuarkusGraalFunction
      Handler: com.lineup.scenario01.function.quarkus.QuarkusFunction
      Runtime: provided.al2
      Policies:
        - AmazonDynamoDBFullAccess

  MicronautFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./micronaut-function
      FunctionName: serverless2049-scenario01-function-MicronautFunction
      Handler: com.lineup.scenario01.function.micronaut.FunctionRequestHandler
      Runtime: java11
      Policies:
        - AmazonDynamoDBFullAccess


  MicronautGraalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./micronaut-function/target/function.zip
      FunctionName: serverless2049-scenario01-function-MicronautGraalFunction
      Handler: com.lineup.scenario01.function.micronaut.Function
      Runtime: provided.al2
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      SkipBuild: True

  DatabaseTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: serverless2049-dynamodb-table-Database
      PrimaryKey:
        Name: id
        Type: String
